// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documentation": {
            "get": {
                "description": "Interactive API documentation with Swagger UI.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "documentation"
                ],
                "summary": "API Documentation",
                "responses": {
                    "200": {
                        "description": "HTML page with Swagger UI",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "db_unavailable",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    }
                }
            }
        },
        "/triage/sessions": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triage"
                ],
                "summary": "Start a triage session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Correlation ID; generated when omitted and echoed back in the response header",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.SessionStateResponse"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "503": {
                        "description": "db_unavailable",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    }
                }
            }
        },
        "/triage/sessions/{session_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triage"
                ],
                "summary": "Get the current session state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID (UUID)",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Correlation ID; generated when omitted and echoed back in the response header",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SessionStateResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request — session_id is not a UUID",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "404": {
                        "description": "session_not_found",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    }
                }
            }
        },
        "/triage/sessions/{session_id}/answers": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triage"
                ],
                "summary": "Submit an answer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID (UUID)",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Correlation ID; generated when omitted and echoed back in the response header",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "description": "Answer to the current question",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SubmitAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_request or option_not_found",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "404": {
                        "description": "session_not_found",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "409": {
                        "description": "question_mismatch (also the losing writer under concurrency) or session_closed",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "413": {
                        "description": "request_too_large — body over 16 KiB",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "422": {
                        "description": "idempotency_key_reused — same key, different payload",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    }
                }
            }
        },
        "/triage/sessions/{session_id}/result": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Triage"
                ],
                "summary": "Get the final triage result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID (UUID)",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Correlation ID; generated when omitted and echoed back in the response header",
                        "name": "X-Request-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResultDTO"
                        }
                    },
                    "400": {
                        "description": "invalid_request — session_id is not a UUID",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "404": {
                        "description": "session_not_found",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "409": {
                        "description": "session_not_complete — the session is still running",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    },
                    "500": {
                        "description": "internal_error",
                        "schema": {
                            "$ref": "#/definitions/apierr.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AnswerRequest": {
            "type": "object",
            "properties": {
                "idempotencyKey": {
                    "description": "IdempotencyKey makes the request safe to retry. Reusing it with a different payload is\nrejected with 422; omitting it means a retry can only be rejected, not replayed.",
                    "type": "string",
                    "maxLength": 255
                },
                "optionId": {
                    "description": "OptionID must be one of that question's options.",
                    "type": "string",
                    "format": "uuid"
                },
                "questionId": {
                    "description": "QuestionID must be the question the session currently waits on.",
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "ready"
                    ]
                }
            }
        },
        "api.OptionDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.QuestionDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.OptionDTO"
                    }
                },
                "prompt": {
                    "type": "string"
                }
            }
        },
        "api.ResultDTO": {
            "type": "object",
            "properties": {
                "primaryDomain": {
                    "description": "PrimaryDomain is null if the safety gate fired before the flow routed into a domain.",
                    "type": "string",
                    "enum": [
                        "DEPRESSION",
                        "ANXIETY",
                        "TRAUMA"
                    ]
                },
                "recommendedAction": {
                    "description": "RecommendedAction distinguishes the two routes to HIGH: IMMEDIATE_SUPPORT is produced\nonly by the safety gate, PRIORITY_SPECIALIST_ASSESSMENT is the most urgent action\nreachable through scoring alone.",
                    "type": "string",
                    "enum": [
                        "SELF_CARE_RESOURCES",
                        "SPECIALIST_ASSESSMENT",
                        "PRIORITY_SPECIALIST_ASSESSMENT",
                        "IMMEDIATE_SUPPORT"
                    ]
                },
                "riskLevel": {
                    "type": "string",
                    "enum": [
                        "LOW",
                        "MEDIUM",
                        "HIGH"
                    ]
                }
            }
        },
        "api.SessionDTO": {
            "type": "object",
            "properties": {
                "currentDomain": {
                    "description": "CurrentDomain is null until the intake answer routes the session into a domain.",
                    "type": "string",
                    "enum": [
                        "DEPRESSION",
                        "ANXIETY",
                        "TRAUMA"
                    ]
                },
                "currentQuestionId": {
                    "description": "CurrentQuestionID is the question the session waits on, null once it is terminal.",
                    "type": "string"
                },
                "highRiskDetected": {
                    "description": "HighRiskDetected is true once the safety gate has fired for this session.",
                    "type": "boolean"
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "description": "Status is IN_PROGRESS while the session accepts answers. COMPLETED and HIGH_RISK are\nterminal; a further answer returns 409 session_closed.",
                    "type": "string",
                    "enum": [
                        "IN_PROGRESS",
                        "COMPLETED",
                        "HIGH_RISK"
                    ]
                }
            }
        },
        "api.SessionStateResponse": {
            "type": "object",
            "properties": {
                "currentQuestion": {
                    "$ref": "#/definitions/api.QuestionDTO"
                },
                "session": {
                    "$ref": "#/definitions/api.SessionDTO"
                }
            }
        },
        "api.SubmitAnswerResponse": {
            "type": "object",
            "properties": {
                "currentQuestion": {
                    "$ref": "#/definitions/api.QuestionDTO"
                },
                "highRisk": {
                    "description": "HighRisk is true when this answer tripped the safety gate.",
                    "type": "boolean"
                },
                "outcome": {
                    "description": "Outcome is a machine-readable status: NEXT_QUESTION, COMPLETED, HIGH_RISK or REPLAYED.",
                    "type": "string",
                    "enum": [
                        "NEXT_QUESTION",
                        "COMPLETED",
                        "HIGH_RISK",
                        "REPLAYED"
                    ]
                },
                "result": {
                    "description": "Result is present for COMPLETED and HIGH_RISK, null while the flow continues.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.ResultDTO"
                        }
                    ]
                },
                "session": {
                    "$ref": "#/definitions/api.SessionDTO"
                }
            }
        },
        "apierr.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the stable machine-readable error code. Clients branch on this.",
                    "type": "string",
                    "enum": [
                        "invalid_request",
                        "option_not_found",
                        "session_not_found",
                        "question_mismatch",
                        "session_closed",
                        "session_not_complete",
                        "idempotency_key_reused",
                        "request_too_large",
                        "route_not_found",
                        "method_not_allowed",
                        "db_unavailable",
                        "internal_error"
                    ]
                },
                "message": {
                    "description": "Message is human-readable and not stable; do not branch on it.",
                    "type": "string"
                },
                "requestId": {
                    "description": "RequestID is the correlation ID, also returned in the X-Request-ID header.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
