// Package docs holds the generated OpenAPI specification and embeds it into the binary so
// the service can serve it without shipping the file alongside.
//
// swagger.json and swagger.yaml are generated by `make docs` from the handler annotations in
// internal/api and the DTO structs themselves — this file is the only hand-written one here.
// Regenerate rather than edit them; a spec written by hand drifts from the wire types on the
// first DTO change and nothing notices.
package docs

import (
	"embed"
	"io/fs"
)

//go:embed swagger.json swagger.yaml
var files embed.FS

// SpecJSON is the OpenAPI 3.1 document in JSON, which is what Swagger UI fetches.
func SpecJSON() ([]byte, error) {
	return fs.ReadFile(files, "swagger.json")
}

// SpecYAML is the same document in YAML, for humans and for code generators.
func SpecYAML() ([]byte, error) {
	return fs.ReadFile(files, "swagger.yaml")
}
